steps:
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/notification-service", "."]
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/notification-service"]
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args: ["run", "deploy", "notification-service", "--image", "gcr.io/$PROJECT_ID/notification-service", "--platform", "managed", "--region", "us-central1", "--allow-unauthenticated"]

options:
    logging: CLOUD_LOGGING_ONLY
